/* Generated by AN DISI Unibo */ 
package it.unibo.weightsensoractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weightsensoractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val sensor = it.unibo.basicdevices.DeviceManager.requestDevice("indoor sensor")
				var weight : Double
				
				if(sensor == null) {
					println("$name | unable to use the sonar")
					System.exit(-1)
				}
				
				sensor as it.unibo.basicweightsensor.WeightSensor
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | started")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						 weight = sensor.readWeight()  
						updateResourceRep( weight.toString()  
						)
						println("$name | weight distance : ${weight}")
					}
					 transition(edgeName="t06",targetState="work",cond=whenDispatch("updatesensorstate"))
				}	 
			}
		}
}
