/* Generated by AN DISI Unibo */ 
package it.unibo.dtfreecounter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Dtfreecounter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 	
				val state : it.unibo.parkingstate.StateReader = it.unibo.parkingstate.MockState
				val DTFREE = 2000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | started")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name | working...")
					}
					 transition(edgeName="t6",targetState="count",cond=whenDispatch("startDtfreeCounter"))
				}	 
				state("count") { //this:State
					action { //it:State
						println("$name | start DTFREE count...")
						stateTimer = TimerActor("timer_count", 
							scope, context!!, "local_tout_dtfreecounter_count", DTFREE )
					}
					 transition(edgeName="t7",targetState="reached",cond=whenTimeout("local_tout_dtfreecounter_count"))   
					transition(edgeName="t8",targetState="count",cond=whenDispatch("startDtfreeCounter"))
				}	 
				state("reached") { //this:State
					action { //it:State
						 if(state.getOutdoorState().equals(`it.unibo.parkingstate`.DoorState.OCCUPIED)) { 
						forward("dtfreeReached", "dtfreeReached(REACHED)" ,"parkingservicestatusgui" ) 
						println("$name | DTFREE reached and outdoor is occupied... Manager has been notified")
						 }  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
