/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.kcproxy

import it.unibo.kcproxy.configuration.ConfigLoader
import it.unibo.kcproxy.proxies.ProxyConfigurationBuilder
import it.unibo.kcproxy.proxies.ProxyContainer
import kotlinx.coroutines.runBlocking

fun main() {
    print("................................\n" +
            "..........__...--...__..........\n" +
            "...........,!~^rr;~!,...........\n" +
            "..........\"*r><^~!!r*,..........\n" +
            ".......~J2woooooIooIowzV=.......\n" +
            ".....:qN~`            .*0o,.....\n" +
            "79X!lQz.````````````````_qQx~H6?\n" +
            "_6@@@@####################@@@@f-\n" +
            ":#2_LD@@@@@@@@@@@@@@@@@@@@0Y,0g-\n" +
            "|@Q,  =B#VYYYYYYYYYYYYo#Q!  v@@~\n" +
            "l@@#Slo#W*!,_.````._\"~*D#I2g@@@r\n" +
            "J@@@@@@@@@@@@@####@@@@@@@@@@@@@v\n" +
            "v#@@@@@@@#p}v\\\\\\\\\\\\vld#@@WPaMQB^\n" +
            "._=======_............,=======_.\n" +
            "-\",,,,\":,,:::=::=!!\"::::\"\"\"::::_\n" +
            "................................")
    println("______ _________________                             \n" +
            "___  //_/_  ____/__  __ \\________________  ______  __\n" +
            "__  ,<  _  /    __  /_/ /_  ___/  __ \\_  |/_/_  / / /\n" +
            "_  /| | / /___  _  ____/_  /   / /_/ /_>  < _  /_/ / \n" +
            "/_/ |_| \\____/  /_/     /_/    \\____//_/|_| _\\__, /  \n" +
            "                                            /____/   ")

    var configs = ConfigLoader.load().getEntries()
    println("KCProxy | Completed loading configuration")

    var proxies = ProxyConfigurationBuilder.buildProxies(configs)
    println("KCProxy | All proxies are builded")

    ProxyContainer.registerAll(proxies)
    println("KCProxy | All proxies registered")

    runBlocking {
        ProxyContainer.startAll()
        println("KCProxy | All proxies started")
    }
    println("KCProxy | Press a key or CTRL+C/D to stop")

    readLine()
    ProxyContainer.stopAll()
    println("KCProxy | Terminated")
}
